### ISSUE TITLE
stop 

### ISSUE THREAD

**Issue by snrertrk** [falconsw/follow-console#1]
örn: 15 kişiyi takip ettirdikten sonra 5 dakika bekletip kodun tekrar çalışmasını nasıl sağlayabiliriz?

**Comment by falconsw** [comment]
kodun en başına var i=1; ile başlatıp  tıklama alanına i++ ekleyerek kaçıncı tıklama olmuş görebilirsin ve sonrasında clear interval ile çalışmayı durdurursun
